[package]
name = "miltr-utils"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A miltr utils library in pure rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.5.0"
